In [2]:
import pandas as pd
fac = pd.read_csv("facilities.csv", index_col="id")

In [3]:
fac.head()

,parcel_id,inactive,name,rentable,type,primary_user,address_number,street,zip,image,neighborhood,council_district,ward,tract,public_works_division,pli_division,police_zone,fire_zone,latitude,longitude
id,,,,,,,,,,,,,,,,,,,,
1,120-J-300,f,57th Street Park Building,f,Storage,Department of Public Works,NaN,57TH ST,NaN,https://tools.wprdc.org/images/pittsburgh/faci...,Upper Lawrenceville,7,10.0,42003101100,2.0,10.0,2.0,5-Mar,40.485666,-79.946450
2,2-H-284,f,Albert Turk Graham Park Shelter,f,Shelter,Department of Public Works,39.0,VINE ST,NaN,https://tools.wprdc.org/images/pittsburgh/faci...,Crawford-Roberts,6,3.0,42003030500,3.0,3.0,2.0,1-Feb,40.440472,-79.984106
3,23-R-157,f,Allegheny Northside Senior Center and Hazlett ...,t,Senior,CitiParks,5.0,ALLEGHENY SQ E,15212.0,https://tools.wprdc.org/images/pittsburgh/faci...,Allegheny Center,1,22.0,42003562700,1.0,22.0,1.0,6-Jan,40.453099,-80.005343
4,10-F-198,f,Ammon Recreation Center,f,Pool,CitiParks,2217.0,BEDFORD AVE,15219.0,https://tools.wprdc.org/images/pittsburgh/faci...,Bedford Dwellings,6,5.0,42003050900,3.0,5.0,2.0,5-Feb,40.448735,-79.977856
5,013-K-314,f,Arlington Field Lights Building,f,Utility,CitiParks,0.0,STERLING ST,15210.0,https://tools.wprdc.org/images/pittsburgh/faci...,South Side Slopes,3,16.0,42003160800,3.0,16.0,3.0,22-Apr,40.418152,-79.974471

In [3]:
print(fac["type"].unique())

['Storage' 'Shelter' 'Senior' 'Pool' 'Utility' 'Activity' 'Restrooms'
 'Service' 'Concession' 'Dugout' 'Pool/Rec' 'Rec Center' 'Office'
 'Pool Closed' 'Firehouse' 'Community' 'Vacant' 'Cabin' 'Medic Station'
 'Training' 'Police' 'Salt Dome' 'Recycling' 'SERVICE' 'STORAGE' 'POLICE'
 'TRAINING' 'OFFICE' nan]

In [14]:
fac['neighborhood'].value_counts()

Highland Park          30
Squirrel Hill South    29
Perry North            20
Brookline              19
Strip District         15
                       ..
Crafton Heights         1
Upper Lawrenceville     1
Stanton Heights         1
Bon Air                 1
West Oakland            1
Name: neighborhood, Length: 75, dtype: int64

In [9]:
fac['type'].value_counts()

Shelter          62
Dugout           42
Concession       32
Firehouse        28
Service          27
Pool             25
Storage          24
Office           23
Utility          19
Activity         18
Restrooms        18
Senior           16
Medic Station    11
Salt Dome         8
Police            8
POLICE            7
Pool/Rec          6
STORAGE           6
Rec Center        6
Cabin             4
Pool Closed       4
Recycling         3
SERVICE           3
Community         3
OFFICE            2
TRAINING          2
Training          2
Vacant            1
Name: type, dtype: int64

In [24]:
type = fac['type']
shelter_mask =  type.str.contains('Shelter',regex=True) 
neighborhood = fac['neighborhood'].value_counts() >=2

<ipython-input-24-bce0dcbea338>:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  both = fac[shelter_mask & neighborhood]

In [3]:
one = pd.DataFrame(fac['neighborhood'].value_counts())
one = one.rename(columns = {'neighborhood':'facility count'})
one

                     facility count
Highland Park                    30
Squirrel Hill South              29
Perry North                      20
Brookline                        19
Strip District                   15
...                             ...
Fineview                          1
West Oakland                      1
Stanton Heights                   1
Homewood North                    1
Bon Air                           1

[75 rows x 1 columns]

In [18]:
two = pd.DataFrame(fac['type'].value_counts())
two

               type
Shelter          62
Dugout           42
Concession       32
Firehouse        28
Service          27
Pool             25
Storage          24
Office           23
Utility          19
Restrooms        18
Activity         18
Senior           16
Medic Station    11
Salt Dome         8
Police            8
POLICE            7
Pool/Rec          6
Rec Center        6
STORAGE           6
Pool Closed       4
Cabin             4
Recycling         3
SERVICE           3
Community         3
OFFICE            2
Training          2
TRAINING          2
Vacant            1

In [27]:
mask1 = fac['neighborhood'] == "Highland Park"
hpark = fac[mask1]
mask2 = hpark['type'].value_counts()
hpark.head
mask2.head()

Shelter     10
Service      4
Storage      3
STORAGE      3
TRAINING     2
Name: type, dtype: int64

In [36]:
mask1 = fac['neighborhood'] == "Squirrel Hill South"
hpark = fac[mask1]
mask2 = hpark['type'].value_counts()
hpark.head
mask2.head(15)

Shelter       12
Office         4
Restrooms      3
Service        2
Activity       2
Cabin          2
Pool           1
Concession     1
Storage        1
Name: type, dtype: int64

In [37]:
mask1 = fac['neighborhood'] == "Perry North"
hpark = fac[mask1]
mask2 = hpark['type'].value_counts()
hpark.head
mask2.head(15)

Shelter       8
Service       2
Dugout        2
Firehouse     1
Concession    1
Office        1
Cabin         1
Salt Dome     1
Restrooms     1
Storage       1
Pool          1
Name: type, dtype: int64

In [34]:
mask1 = fac['neighborhood'] == "Brookline"
hpark = fac[mask1]
mask2 = hpark['type'].value_counts()
hpark.head
mask2.head(10)

Dugout        7
Shelter       3
Concession    3
Pool          2
Firehouse     1
Pool/Rec      1
Rec Center    1
Storage       1
Name: type, dtype: int64

In [35]:
mask1 = fac['neighborhood'] == "Strip District"
hpark = fac[mask1]
mask2 = hpark['type'].value_counts()
hpark.head
mask2.head(10)

Service      5
Office       4
SERVICE      2
Firehouse    1
Salt Dome    1
Storage      1
Training     1
Name: type, dtype: int64

In [5]:
##rankings of neghiborhoods with the highest facilities
one

                     facility count
Highland Park                    30
Squirrel Hill South              29
Perry North                      20
Brookline                        19
Strip District                   15
...                             ...
Fineview                          1
West Oakland                      1
Stanton Heights                   1
Homewood North                    1
Bon Air                           1

[75 rows x 1 columns]